[versions]
paper-api = "1.21.11-R0.1-SNAPSHOT"
adventure-api = "4.17.0"
adventure-minimessage = "4.17.0"
shadow = "8.1.1"
run-task = "2.3.1"
paperweight = "2.0.0-beta.21"
junit = "5.10.2"
mockito = "5.11.0"

[libraries]
paper-api = { module = "io.papermc.paper:paper-api", version.ref = "paper-api" }
adventure-api = { module = "net.kyori:adventure-api", version.ref = "adventure-api" }
adventure-minimessage = { module = "net.kyori:adventure-text-minimessage", version.ref = "adventure-minimessage" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
mockito-core = { module = "org.mockito:mockito-core", version.ref = "mockito" }
mockito-junit-jupiter = { module = "org.mockito:mockito-junit-jupiter", version.ref = "mockito" }

[plugins]
shadow = { id = "com.github.johnrengelman.shadow", version.ref = "shadow" }
run-task = { id = "xyz.jpenilla.run-paper", version.ref = "run-task" }
paperweight = { id = "io.papermc.paperweight.userdev", version.ref = "paperweight" }
